### ISSUE TITLE
Please clean up your requirements.

### ISSUE THREAD

**Issue by amcgregor** [kevinadhiguna/ip-revealer#1]
Exactly the same problem as per: kevinadhiguna/link-shortener#1 and kevinadhiguna/instagram-profpic-downloader#1 and kevinadhiguna/body-mass-index-calculator#1

Low quality bulk library creation with no use of the referenced libraries is pure spam.  Please correct this.

**Comment by kevinadhiguna** [comment]
Hello @amcgregor , thank you for opening this issue !
I just removed the `requirements.txt` in the [latest commit](https://github.com/kevinadhiguna/ip-revealer/commit/0ed13bdc7446dcbb7f28923a6e6e7465d67184ad) as it is not required. Please let me know if there are any problems.

**Comment by amcgregor** [comment]
Thank you very much, and apologies for the cross-project e-mail notification spam I must have triggered; thought you may wish to individually track corrections.

Thank you again! (Time for another spam-wave. 😭)
